[package]
name = "cobalt_xml_merge"
version = "0.5.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1"
differ = "1"
quick-xml = "^0.30"
anyhow = "1"
similar = "2.3.0"

[dev-dependencies]
criterion = "0.5"
lazy_static = "1"

[profile.bench]
lto = "thin"

[[bench]]
name = "merge_benchmark"
harness = false
