[package]
name = "cobalt_xml_merge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
differ = "1"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "merge_benchmark"
harness = false